ng-build:
  image: node:8.1.4-alpine
  stage: build
  script:
   - yarn
   - yarn global add @angular/cli
   - ng build

maven-build:
  image: maven:3.5.0-jdk-8-alpine
  stage: build
  dependencies: [ng-build]
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
