stages:
- frontend-build
- backend-build

cache:
  untracked: true
  paths:
    - .yarn-cache

ng-build:
  image: node:8.1.4-alpine
  stage: frontend-build
  script:
   - yarn config set cache-folder .yarn-cache
   - yarn
   - ng build
  artifacts:
      paths:
        - target/ng-dist

maven-build:
  image: maven:3.5.0-jdk-8-alpine
  dependencies: [ng-build]
  stage: backend-build
  script:
  - ls -al target/
  - mvn package -B
  artifacts:
    paths:
      - target/*.jar
