variables:
  MAVEN_OPTS: "-Dmaven.repo.local=repository/.m2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  untracked: true
  paths:
    - repository

ng-build:
  image: alexsuch/angular-cli:1.2.0
  stage: build
  script:
   - yarn config set cache-folder repository/.yarn
   - ng build
  artifacts:
      paths:
        - target
        - node_modules

maven-build:
  image: maven:3.5.0-jdk-8-alpine
  stage: build
  script:
  - mvn compile -B -DskipTests=true
  artifacts:
    paths:
      - target

ng-test:
  image: alexsuch/angular-cli:1.2.0
  dependencies: [ng-build]
  stage: test
  script:
   - yarn config set cache-folder repository/.yarn
   - ng test
  artifacts:
    paths:
      - target
      - node_modules

maven-test:
  image: maven:3.5.0-jdk-8-alpine
  dependencies: [maven-build]
  stage: test
  script:
  - mvn test -B
  artifacts:
    paths:
      - target

package:
  image: maven:3.5.0-jdk-8-alpine
  dependencies: [ng-test,maven-test]
  stage: deploy
  script:
  - mvn package -B -DskipTests=true
  artifacts:
    paths:
      - target/*.jar
