stages:
- frontend-build
- backend-build

ng-build:
  image: node:8.1.4-alpine
  stage: frontend-build
  script:
   - yarn
   - yarn global add @angular/cli
   - ng build

maven-build:
  image: maven:3.5.0-jdk-8-alpine
  dependencies: [ng-build]
  stage: backend-build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
