variables:
  MAVEN_OPTS: "-Dmaven.repo.local=repository/.m2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  untracked: true
  paths:
    - repository

ng-build:
  image: node:8.1.4-alpine
  stage: build
  script:
   - yarn config set cache-folder repository/.yarn
   - yarn
   - yarn global add @angular/cli
   - ng build
  artifacts:
      paths:
        - target

maven-build:
  image: maven:3.5.0-jdk-8-alpine
  stage: build
  script:
  - mvn compile -B -DskipTests=true
  artifacts:
    paths:
      - target


ng-test:
  image: node:8.1.4-alpine
  dependencies: [ng-build]
  stage: test
  script:
  - ng test
  artifacts:
    paths:
      - target

maven-test:
  image: maven:3.5.0-jdk-8-alpine
  dependencies: [maven-build]
  stage: test
  script:
  - mvn test -B
  artifacts:
    paths:
      - target

package:
  image: maven:3.5.0-jdk-8-alpine
  dependencies: [ng-test,maven-test]
  stage: deploy
  cache:
    untracked: true
    paths:
     - /.m2/repo
  variables:
    MAVEN_OPTS: -Dmaven.repo.local=/.m2/repo
  script:
  - mvn package -B -DskipTests=true
  artifacts:
    paths:
      - target/*.jar
